### ISSUE TITLE
Cannot see Duo Emulator after installed SDK preview with VS2019

### ISSUE THREAD

**Issue by winecos** [microsoft/surface-duo-sdk-xamarin-samples#2]
hi , guys .
I cannot see any Surface Duo Emulator in Visual Studio 2019 . 

My dev environment : 
OS : Windows 10(19555.0) 
Hardware : Surface Book 2 

The screenshots as bellow 
![Annotation 2020-02-01 225210](https://user-images.githubusercontent.com/9930176/73594822-ddd86980-454c-11ea-92a3-c5a8d3721d08.png)

so , does any solutions for this issue ?

**Comment by tscholze** [comment]
@winecos 

**Did you:**
- Edit the run.bat script as mentioned in the Docs article?
- Did you start the emulator and can you see it running?

**Comment by winecos** [comment]
@tscholze  thanks .

- Edit the run.bat script as mentioned in the Docs article?
==> yes . added the path of Android SDK.
- Did you start the emulator and can you see it running?
==> yes , starting the emulator and then open the Xamarin.Duo.Samples.sln file . but, it haven't 
![Annotation 2020-02-04 134843](https://user-images.githubusercontent.com/9930176/73717551-206c9280-4755-11ea-99cb-7a76b4ce4331.png)

Thanks.

**Comment by tscholze** [comment]
Good morning @winecos,

I meant if you edited the `run.bat` like mentioned in [Docs article (see section "Xamarin")](https://docs.microsoft.com/en-us/dual-screen/android/use-emulator?tabs=windows). That means to remove the port parameter of a call that's included in the file.

Yes is see the emulator running and I'm able to select in VS.

If you have any further problems, you might want to visit the official technet community of the SDK ([see link)](https://techcommunity.microsoft.com/t5/surface-duo-sdk/bd-p/SurfaceDuoSDK).

**Comment by winecos** [comment]
@tscholze  Thanks very much !
if remove the port parameter of a call in run.bat , can't start the Surface Duo Emulator on the desktop icon.

**Comment by tscholze** [comment]
@winecos 
than let us revert all.

What happens when you just copy past (and edit the android path) and run the run.bat from a Command Line? This should print out some errors which might be wrong.

You can also reset the emulator by running the clean start skript in the same folder as the run script is.

**Comment by owlstack** [comment]
Sorry to hijack this thread but I can't see the Surface Duo emulator as one of the options but this time on Visual Studio for Mac. I do have Surface Duo emulator running just fine in the background however. How can I get the Xamarin.Forms sample to run via VS for Mac?

**Comment by tscholze** [comment]
@winecos Is now everything running as you expect?

**Comment by conceptdev** [comment]
The latest emulator (since this issue) has a separate batch file specifically for Visual Studio `run_vs.bat`, hopefully this makes it easier to use. Please raise a new issue if needed.
